// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmK5HfHNtexMy64ISNGt1pYiLPfbU8eno',
    appId: '1:740596525799:web:103f0d8f0f524fa9f29042',
    messagingSenderId: '740596525799',
    projectId: 'mydaftari-3c3a1',
    authDomain: 'mydaftari-3c3a1.firebaseapp.com',
    storageBucket: 'mydaftari-3c3a1.appspot.com',
    measurementId: 'G-GK98LFZC9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUNEN1IGxAZIVu7ib181KKEuQ__bGSBIw',
    appId: '1:740596525799:android:a571a880f08b84f7f29042',
    messagingSenderId: '740596525799',
    projectId: 'mydaftari-3c3a1',
    storageBucket: 'mydaftari-3c3a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq7DwbIx3jSBJellRR3l1uLFjTwR-l5nk',
    appId: '1:740596525799:ios:bc1dfad0e8ba7505f29042',
    messagingSenderId: '740596525799',
    projectId: 'mydaftari-3c3a1',
    storageBucket: 'mydaftari-3c3a1.appspot.com',
    iosClientId: '740596525799-chdqobd96kjpg9gdmihuri214guqr2nu.apps.googleusercontent.com',
    iosBundleId: 'com.wavesinall.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq7DwbIx3jSBJellRR3l1uLFjTwR-l5nk',
    appId: '1:740596525799:ios:bc1dfad0e8ba7505f29042',
    messagingSenderId: '740596525799',
    projectId: 'mydaftari-3c3a1',
    storageBucket: 'mydaftari-3c3a1.appspot.com',
    iosClientId: '740596525799-chdqobd96kjpg9gdmihuri214guqr2nu.apps.googleusercontent.com',
    iosBundleId: 'com.wavesinall.mynotes',
  );
}
//scsss